apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-uploads
  namespace: planka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
