apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - name: adb
      port: 5555
      targetPort: 5555
    - name: console
      port: 5554
      targetPort: 5554
    - name: vnc
      port: 5900
      targetPort: 5900
    - name: novnc
      port: 6080
      targetPort: 6080
