apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-startup
  namespace: {{ .Values.namespace }}
data:
  startup.sh: |
    {{- $resolution := .Values.xorg.resolution -}}
    {{- $resolutionParts := regexSplit "x" $resolution -1 -}}
    {{- $w := (index $resolutionParts 0 | toString) -}}
    {{- $h := (index $resolutionParts 1 | toString) -}}
    #!/bin/bash
    set -e
    export DISPLAY={{ .Values.xorg.display }}
    export MESA_LOADER_DRIVER_OVERRIDE="${MESA_LOADER_DRIVER_OVERRIDE:-iris}"
    export LIBGL_ALWAYS_SOFTWARE=0
    export DRI_PRIME=0
    if [[ -f /usr/share/vulkan/icd.d/intel_icd.x86_64.json ]]; then
      export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json
    fi

    INTEL_CARD=""; BUSID=""
    for c in /dev/dri/card*; do
      [[ -e "$c" ]] || continue
      devpath="/sys/class/drm/$(basename "$c")/device"
      vend="$(cat "${devpath}/vendor" 2>/dev/null || true)"
      if [[ "$vend" == "0x8086" ]]; then
        INTEL_CARD="$c"
        slot="$(grep -m1 '^PCI_SLOT_NAME=' "${devpath}/uevent" 2>/dev/null | cut -d= -f2)"
        if [[ -n "$slot" ]]; then
          BB=$((16#${slot:5:2})) ; DD=$((16#${slot:8:2})) ; F=${slot:11:1}
          BUSID="PCI:${BB}:${DD}:${F}"
        fi
        break
      fi
    done
    if [[ -z "$INTEL_CARD" || -z "$BUSID" ]]; then
      echo "[Xorg] Intel iGPU not found in /dev/dri; aborting." >&2
      ls -l /dev/dri || true
      exit 1
    fi
    echo "[Xorg] Using Intel ${INTEL_CARD} (BusID ${BUSID})"

    mkdir -p /etc/X11/xorg.conf.d
    cat >/etc/X11/xorg.conf.d/00-server.conf <<'EOF'
    Section "ServerFlags"
      Option "AutoAddGPU" "false"
    EndSection
    EOF

    cat >/etc/X11/xorg.conf.d/10-modesetting.conf <<EOF
    Section "Device"
      Identifier "iGPU"
      Driver "modesetting"
      BusID "${BUSID}"
      Option "AccelMethod" "glamor"
      Option "DRI" "3"
      Option "PrimaryGPU" "true"
      Option "kmsdev" "${INTEL_CARD}"
    EndSection
    EOF

    cat >/etc/X11/xorg.conf.d/20-screen.conf <<EOF
    Section "Monitor"
        Identifier "Monitor0"
        Option "PreferredMode" "{{ .Values.xorg.resolution }}"
    EndSection
    Section "Screen"
        Identifier "Screen0"
        Device     "iGPU"
        Monitor    "Monitor0"
        DefaultDepth 24
        SubSection "Display"
            Depth 24
            Virtual {{ $w }} {{ $h }}
            Modes "{{ .Values.xorg.resolution }}"
        EndSubSection
    EndSection
    EOF

    Xorg {{ .Values.xorg.display }} -ac -noreset +extension GLX +extension RANDR -logfile /var/log/Xorg.0.log &
    # Wait for X socket to be ready
    for i in {1..60}; do
      [[ -S /tmp/.X11-unix/X0 ]] && break
      sleep 0.5
    done
    mkdir -p /root/.fluxbox
    cat >/root/.fluxbox/init <<'EOF'
    session.screen0.windowPlacement: RowSmartPlacement
    session.screen0.rowPlacementDirection: LeftToRight
    session.screen0.colPlacementDirection: TopToBottom
    EOF
    fluxbox >/var/log/fluxbox.log 2>&1 &
    x11vnc -display {{ .Values.xorg.display }} -noshm -noxdamage -shared -forever -listen 0.0.0.0 -rfbport {{ .Values.vnc.port }} >/var/log/x11vnc.log 2>&1 &

    # Keep container alive and stream logs
    touch /var/log/Xorg.0.log /var/log/x11vnc.log /var/log/fluxbox.log
    exec tail -F /var/log/Xorg.0.log /var/log/x11vnc.log /var/log/fluxbox.log
