apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/finalquest/argo-k8s-pods.git # ← tu repo real
    targetRevision: main                             # ← o master u otro branch
    path: prometheus/servicemonitor                  # ← según la carpeta que mostraste
  destination:
    server: https://kubernetes.default.svcb
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
