apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/finalquest/argo-k8s-pods.git
    targetRevision: main
    path: echo-tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }