apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/finalquest/argo-k8s-pods.git
    targetRevision: main
    path: grocy
  destination:
    server: https://kubernetes.default.svc
    namespace: grocy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
