apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ha-dash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/finalquest/argo-k8s-pods
    targetRevision: main
    path: ha-dash
  destination:
    server: https://kubernetes.default.svc
    namespace: ha-dash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
