apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/finalquest/argo-k8s-pods.git
    targetRevision: main
    path: inventory/config/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: inventory
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
