apiVersion: v1
kind: Service
metadata:
  name: android-emulator13-service
spec:
  selector:
    app: android
  type: NodePort
  ports:
    - name: vnc
      port: 5900
      targetPort: 5900
      nodePort: 31091
      protocol: TCP
    - name: vnc-web
      port: 6080
      targetPort: 6080
      nodePort: 31082
    - name: adb
      port: 5555
      targetPort: 5555
      nodePort: 31556
    - name: emulator-console
      port: 5554
      targetPort: 5554
      nodePort: 31564
