apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-maestro-orchestrator
  labels:
    app.kubernetes.io/name: maestro-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: maestro-orchestrator-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Sensitive values should be base64 encoded
  gitPat: {{ .Values.secrets.gitPat | b64enc | quote }}
  gitAppiumPat: {{ .Values.secrets.gitAppiumPat | b64enc | quote }}
