apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-maestro-orchestrator
  labels:
    app.kubernetes.io/name: maestro-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: maestro-orchestrator-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    last-sync-trigger: "20250802" # <-- Etiqueta trivialI
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: maestro-orchestrator
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-maestro-orchestrator-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maestro-orchestrator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash"]
          stdin: true
          tty: true
          env:
            - name: MAX_PARALLEL_WORKERS
              value: {{ .Values.config.maxParallelWorkers | quote }}
            - name: APPIUM_BRANCH
              value: {{ .Values.config.appiumBranch | quote }}
            - name: BUILD_DIR
              value: {{ .Values.config.buildDir | quote }}
            - name: GIT_USER
              value: {{ .Values.config.gitUser | quote }}
            - name: GIT_URL
              value: {{ .Values.config.gitUrl | quote }}
            - name: GIT_APPIUM_URL
              value: {{ .Values.config.gitAppiumUrl | quote }}
            - name: FLOWS_DIR
              value: {{ .Values.config.flowsDir | quote }}
            - name: ADB_PARALLELISM
              value: {{ .Values.config.adbParallelism | quote }}
            - name: REBOOT_EMULATORS
              value: {{ .Values.config.rebootEmulators | quote }}
            - name: APK_REGISTRY
              value: {{ .Values.config.apkRegistry | quote }}
            - name: APK_PATH
              value: {{ .Values.config.apkPath | quote }}
            - name: RHOST
              value: {{ .Values.config.redis.host | quote }}
            - name: RPORT
              value: {{ .Values.config.redis.port | quote }}
            - name: GIT_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maestro-orchestrator
                  key: gitPat
            - name: GIT_APPIUM_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maestro-orchestrator
                  key: gitAppiumPat
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-maestro-orchestrator-scripts
            defaultMode: 0755 # Make scripts executable
      restartPolicy: Always
