apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-emulator-14
  namespace: android-emulators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-emulator-14
  template:
    metadata:
      labels:
        app: android-emulator-14
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: emulator
          image: budtmo/docker-android:emulator_14.0
          ports:
            - containerPort: 6080
            - containerPort: 4723
            - containerPort: 5554
            - containerPort: 5555
            - containerPort: 6090
          env:
            - name: DEVICE
              value: "Samsung Galaxy S10"
            - name: AUTO_RECORD
              value: "false"
            - name: ENABLE_VNC
              value: "true"
            - name: WEB_VNC
              value: "true"
          securityContext:
            privileged: true
          volumeMounts:
            - name: kvm
              mountPath: /dev/kvm
      volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
