apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: android-emulator-14
  namespace: android-emulators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-emulator-14
  serviceName: android-emulator-14
  template:
    metadata:
      labels:
        app: android-emulator-14
    spec:
      nodeSelector:
        role: worker
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: android-emulator-14
      containers:
        - name: emulator
          image: harbor:8080/android-emulators/emulator-with-heartbeat:14
          imagePullPolicy: Always
          ports:
            - containerPort: 6080
              name: vnc-web
            - containerPort: 5900
              name: vnc
            - containerPort: 5554
            - containerPort: 5555
              name: adb
            - containerPort: 6090
          env:
            - name: DEVICE
              value: "Samsung Galaxy S10"
            - name: AUTO_RECORD
              value: "false"
            - name: ENABLE_VNC
              value: "false"
            - name: WEB_VNC
              value: "false"
            - name: RHOST
              value: "redis"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "2000m"
              memory: "3Gi"
          volumeMounts:
            - name: kvm
              mountPath: /dev/kvm
      volumes:
        - name: kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
