apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-data
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
