apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-orchestrator
  namespace: android-emulators
  labels:
    app: maestro-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro-orchestrator
  template:
    metadata:
      labels:
        app: maestro-orchestrator
    spec:
      containers:
        - name: orchestrator
          image: harbor:8080/tools/maestro-orchestrator:slim-v1
          imagePullPolicy: Always
          command: ["bash"]
          stdin: true
          tty: true
      restartPolicy: Always
