apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librespeed-data
  namespace: speedtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
