apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-metrics
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  type: ClusterIP
  selector:
    app: vaultwarden
  ports:
    - name: metrics
      port: 80
      targetPort: 80
      protocol: TCP