apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: logging
spec:
  type: NodePort
  selector:
    app: fluent-bit
  ports:
    - name: syslog-udp
      protocol: UDP
      port: 5140
      targetPort: 5140
      nodePort: 30514
    - name: syslog-tcp
      protocol: TCP
      port: 5140
      targetPort: 5140
      nodePort: 30515
