apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-downloads-nfs
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-manual
  nfs:
    server: 10.1.0.152
    path: /data/exports/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-manual
  volumeName: pv-downloads-nfs