apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-biblioteca-secreta-nfs
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-manual
  mountOptions:
    - vers=4
  nfs:
    server: 10.1.0.152
    path: /data/exports/media/books/Biblioteca-Secreta-2026
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biblioteca-secreta-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: nfs-manual
  volumeName: pv-biblioteca-secreta-nfs