apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
