apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tokyo-bot-data
  namespace: tokyo-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
