apiVersion: v1
kind: Service
metadata:
  name: pcnt-doc-rag-postgres
  namespace: pcnt-doc-rag
spec:
  type: NodePort
  selector:
    app: pcnt-doc-rag-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
