nameOverride: android-emulator-13

image:
  tag: "13-gpu"

resources:
  requests:
    cpu: "2000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "6Gi"

gpu:
  enabled: true

nodeSelector:
  gpu: intel