apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        media-node: "true"
      securityContext:
        fsGroup: 1000
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Argentina/Buenos_Aires"
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /movies
            - name: scripts
              mountPath: /scripts
            - name: jellyfin-secret
              mountPath: /scripts/secret
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-nfs
        - name: movies
          persistentVolumeClaim:
            claimName: movies-nfs
        - name: scripts
          configMap:
            name: radarr-scripts
            defaultMode: 0755
        - name: jellyfin-secret
          secret:
            secretName: jellyfin-api-key
            optional: true
