apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - pv-pvc-movies-nfs.yaml
  - pvc.yaml
  - deployment-radarr.yaml
  - service-radarr.yaml
  - deployment-jellyfin.yaml
  - service-jellyfin.yaml
  - deployment-jellyseerr.yaml
  - service-jellyseerr.yaml
  - deployment-bazarr.yaml
  - service-bazarr.yaml
  - ingress.yaml
